language: node_js
node_js:
- 0.1
- 0.11
notifications:
  irc: irc.freenode.org#pixelpolishers
deploy:
  provider: npm
  api_key:
    secure: E+sGUFMNUSHs+qPU0xw9+MgLfBx0mm2CWjIHisQUxszeMP9NVNRccg+qm1gUpkMdMIagWtjZ8uFEbm7GD1OmQpxiwXZ9sHDtefjGGw+pb+unvhzYhDyXvyDyoJ14VTtS5lVT6U1TjiMWMW38bUTVifm56fci9acVAtYUDpGYZ5c=
