sudo: false
language: php
cache:
  directories:
  - "$HOME/.composer/cache"
  - vendor
matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
    env:
    - EXECUTE_DEPLOYMENT=true
  - php: 7
  - php: hhvm
  allow_failures:
  - php: hhvm
before_install:
- openssl aes-256-cbc -K $encrypted_6dce21a6bfd4_key -iv $encrypted_6dce21a6bfd4_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
- openssl aes-256-cbc -K $encrypted_d277d4c7314e_key -iv $encrypted_d277d4c7314e_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
- phpenv config-rm xdebug.ini
- composer self-update
install:
- travis_retry composer install --no-interaction
- composer info -i
script:
- "./vendor/bin/phpunit"
after_success:
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST
  == 'false' ]]; then composer install --no-dev ; fi
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST
  == 'false' ]]; then ./bin/deploy.sh ; fi
notifications:
  email: true
